### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by find-happiness** [eneim/Toro#105]
FATAL EXCEPTION: ExoPlayerImplInternal:Handler
                                                                     Process: forked.app.id.debug, PID: 24128
                                                                     java.lang.NullPointerException
                                                                         at com.google.android.exoplayer2.source.ExtractorMediaSource.onSourceInfoRefreshed(ExtractorMediaSource.java:179)
                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod.maybeFinishPrepare(ExtractorMediaPeriod.java:408)
                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod.access$000(ExtractorMediaPeriod.java:49)
                                                                         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$1.run(ExtractorMediaPeriod.java:120)
                                                                         at android.os.Handler.handleCallback(Handler.java:733)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by eneim** [comment]
This relates to [this issue from ExoPlayer](https://github.com/google/ExoPlayer/issues/1914). I didn't push the update with 2.0.3, but you can exclude it from Toro, and add Exo 2.0.3 again.
