### ISSUE TITLE
App run slow when fast scroll down when use branch "release/v2.0.0-RC4" or crash app in branch "release/v2.1.0" with url special

### ISSUE THREAD

**Issue by sonvp** [eneim/Toro#146]
Hi eneim.
I meet bug below when change url
"http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"
into 
"http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism"

My device 
- Version 6.0.1
- Sony Z3+ Dual

**Comment by eneim** [comment]
Hi, do you have the crash log? Can you confirm your link works well with ExoPlayer?

**Comment by sonvp** [comment]
- "Can you confirm your link works well with ExoPlayer?"
==> Yes. I take link url from https://github.com/google/ExoPlayer/blob/release-v1/demo/src/main/java/com/google/android/exoplayer/demo/Samples.java and It works well in exoplayer
- In  ""release/v2.1.0" it show log error:

```
ATAL EXCEPTION: main
                                                                   Process: forked.app.id.debug, PID: 2124
                                                                   java.lang.IndexOutOfBoundsException
                                                                       at com.google.android.exoplayer2.Timeline$1.getWindow(Timeline.java:107)
                                                                       at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:161)
                                                                       at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:148)
                                                                       at im.ene.toro.exoplayer2.ExoVideoView.releasePlayer(ExoVideoView.java:422)
                                                                       at im.ene.toro.exoplayer2.ExoVideoViewHolder.releasePlayer(ExoVideoViewHolder.java:75)
                                                                       at im.ene.toro.PlayerViewHelper.onDetachedFromWindow(PlayerViewHelper.java:78)
                                                                       at im.ene.toro.exoplayer2.ExoVideoViewHolder.onDetachedFromWindow(ExoVideoViewHolder.java:56)
                                                                       at im.ene.toro.ToroAdapter.onViewDetachedFromWindow(ToroAdapter.java:50)
                                                                       at im.ene.toro.ToroAdapter.onViewDetachedFromWindow(ToroAdapter.java:29)
                                                                       at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:6744)
                                                                       at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:708)
                                                                       at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
```

**Comment by eneim** [comment]
if you are working on a fork, please take a look at ExoVideoView line 40x (in the crash log) and fix the IndexOutOfBoundException <- work around for now. I will fix it later on my ongoing branch.

**Comment by sonvp** [comment]
- Sorry, Bug log error above happen when I test in branch "dev-v2" and I deleting the wrong code when build app.
- But I still get an error as image below when fast scroll down or up with link url "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism" in branch "release/v2.0.0-RC4" and "release/v2.1.0"

![device-2017-01-20-173203](https://cloud.githubusercontent.com/assets/8717317/22146580/b77bd75a-df37-11e6-98dc-2b9627baab00.png)

**Comment by eneim** [comment]
@sonvp Can you checkout branch **dev-v3** and try it again?

**Comment by sonvp** [comment]
In branch "dev-v3" when I build app , I get error in class "ExoVideoView.java" .I have to change exoPlayer2Version = 'r2.1.1'==>  exoPlayer2Version = 'r2.0.4'. And run app, I get log error below when fast scroll down or up with link url "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism"

Log Error:
  ```
java.lang.IndexOutOfBoundsException
                                                                         at com.google.android.exoplayer2.Timeline$1.getWindow(Timeline.java:107)
                                                                         at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:161)
                                                                         at com.google.android.exoplayer2.Timeline.getWindow(Timeline.java:148)
                                                                         at im.ene.toro.exoplayer2.ExoVideoView.releasePlayer(ExoVideoView.java:421)
                                                                         at im.ene.toro.exoplayer2.ExoVideoViewHolder.releasePlayer(ExoVideoViewHolder.java:75)
                                                                         at im.ene.toro.PlayerViewHelper.onDetachedFromWindow(PlayerViewHelper.java:78)
                                                                         at im.ene.toro.exoplayer2.ExoVideoViewHolder.onDetachedFromWindow(ExoVideoViewHolder.java:56)
                                                                         at im.ene.toro.ToroAdapter.onViewDetachedFromWindow(ToroAdapter.java:50)
                                                                         at im.ene.toro.ToroAdapter.onViewDetachedFromWindow(ToroAdapter.java:29)
```

**Comment by eneim** [comment]
Hmm, @sonvp it is weird, can you make a clean clone for dev-v3? I have updated ExoVideoView to match latest ExoPlayer update though. Please clear stuff and rebuild to prevent cache :D.

**Comment by sonvp** [comment]
I had rebuild project but still not solve problem . If i not change exoPlayer2Version = 'r2.0.4' , it will show error :
- Class 'ComponentListener' must either be declared abstract or implement abstract method 'onTracksChanged(TrackGroupArray, TrackSelectionArray)' in 'EventListener
- Cannot resolve constructor 'DefaultTrackSelector(android.os.Handler, com.google.android.exoplayer2.trackselection.TrackSelection.Factory)'.

**Comment by eneim** [comment]
@sonvp here is server version of dev-v3 ExoVideoView: [link](https://github.com/eneim/Toro/blob/dev-v3/toro-ext-exoplayer2/src/main/java/im/ene/toro/exoplayer2/ExoVideoView.java#L117) which already has "onTracksChanged" implemented. Can you confirm the content? Please make sure you are on sync with origin or upstream **dev-v3** branch :-?

**Comment by sonvp** [comment]
Thank @eneim . I think mistake something .I checkout again branch "dev-v3" and test app. I not see errors above.
Thank again.
