### ISSUE TITLE
java.lang.NoClassDefFoundError: im.ene.lab.toro.player.widget.ToroVideoView$1

### ISSUE THREAD

**Issue by j-a-s-o-n** [eneim/Toro#152]
I has project which uses Toro V2.0. All worked fine, but few days ago I tried build new version of app and was surprised to see empty RecyclerView. I debugged app an got this issue on all my devices Nexus 5 and Lenovo K50. I'm sure that it wasn't few days ago. All apk files built before, works fine.

java.lang.NoClassDefFoundError: im.ene.lab.toro.player.widget.ToroVideoView$1
                                                                           at im.ene.lab.toro.player.widget.ToroVideoView.<init>(ToroVideoView.java:65)
                                                                           at com.shared.recipes.holders.FbItemViewHolder.createViewHolder(FbItemViewHolder.java:88)
                                                                           at com.shared.recipes.adapters.FeedAdapter.createVideoViewHolder(FeedAdapter.java:166)
                                                                           at com.shared.recipes.adapters.FeedAdapter.onCreateViewHolder(FeedAdapter.java:242)
                                                                           at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6073)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5243)
                                                                           at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5153)
                                                                           at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
                                                                           at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
                                                                           at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
                                                                           at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
                                                                           at com.shared.recipes.helpers.PreCachingLinearLayoutManager.onLayoutChildren(PreCachingLinearLayoutManager.java:47)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3374)
                                                                           at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3183)
                                                                           at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3627)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:630)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                                           at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                                           at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1364)
                                                                           at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:846)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                           at android.view.View.layout(View.java:16975)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5590)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                           at android.view.View.layout(View.java:16975)

buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {
    compileSdkVersion 24
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId ""
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 15
        versionName "1.0"
        vectorDrawables.useSupportLibrary = true

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    dexOptions {
        incremental true
        javaMaxHeapSize "12g"
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'

    compile 'com.android.support:multidex:1.0.1'

    compile "im.ene.lab:toro:2.0.0-SNAPSHOT"
    compile "im.ene.lab:toro-player:2.0.0-SNAPSHOT"
    compile "im.ene.lab:toro-ext:2.0.0-SNAPSHOT"

    compile 'com.jakewharton:butterknife:8.4.0'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:preference-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    compile "com.android.support:gridlayout-v7:24.2.1"
    compile 'com.google.code.gson:gson:2.4.0'

    compile 'com.facebook.android:facebook-android-sdk:4.+'
    compile 'com.facebook.android:audience-network-sdk:4.+'
    compile 'com.google.firebase:firebase-core:9.6.1'
    compile 'com.google.firebase:firebase-crash:9.6.1'
    compile 'com.google.firebase:firebase-config:9.6.1'
    compile 'com.google.android.gms:play-services-base:9.6.1'
    compile 'com.google.android.gms:play-services-ads:9.6.1'
    compile 'com.android.support:cardview-v7:24.2.1'
    compile('com.github.evgenyneu:js-evaluator-for-android:v1.0.4') {
        exclude module: 'appcompat-v7'
    }
    compile 'com.wunderlist:sliding-layer:1.2.5'
    compile 'me.gujun.android.taggroup:library:1.4@aar'
    compile 'com.github.frank-zhu:pullzoomview:1.0.0'
    compile 'me.grantland:autofittextview:0.2.+'
    compile 'jp.wasabeef:recyclerview-animators:2.2.4'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.5@aar') {
        transitive = true;
    }
}
apply plugin: 'com.google.gms.google-services'

**Comment by eneim** [comment]
Try update to Toro 2.1.0 and update your xml since the package name has changed.
