### ISSUE TITLE
Getting NullPointerException when calling  toro.register(RecylerViewInstance);

### ISSUE THREAD

**Issue by AmanChugh** [eneim/Toro#166]
java.lang.NullPointerException: Attempt to read from field 'java.util.Map im.ene.toro.Toro.mViews' on a null object reference
                                                                      at im.ene.toro.Toro.register(Toro.java:167)
                                                                      at com.vylt.andorid.fragments.FeaturedFragment.initViews(FeaturedFragment.java:59)
                                                                      at com.vylt.andorid.fragments.FeaturedFragment.onCreateView(FeaturedFragment.java:50)

**Comment by eneim** [comment]
@AmanChugh Please follow the template, provide more information.

**Comment by AmanChugh** [comment]
Sorry, I did not init Toro in application class.

**Comment by AmanChugh** [comment]
Can you please tell me how to add Sticky Headers with RecyclerView.

**Comment by eneim** [comment]
@AmanChugh Sorry I could not do that, you can google it or ask on StackOverflow ...

**Comment by AmanChugh** [comment]
ok. thanks.
