### ISSUE TITLE
NPE when unregistering 

### ISSUE THREAD

**Issue by supes** [eneim/Toro#193]
In some occasions I'm getting this NPE.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'buy bur.g()' on a null object reference
       at im.ene.toro.Toro.unregister(Toro.java:223)
       at my.package.fragment
       at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2418)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1381)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.FragmentManagerImpl.dispatchDestroyView(FragmentManager.java:2943)
       at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2414)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1381)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
       at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

In the onDestroy of my fragment I call Toro.unregister(recyclerView);
Before that I check if the recyclerView is not null and if Toro.register(recyclerView); has been called. 
But it keeps crashing in the unregister method on the null check of manager.getPlayer(), for some reason the manager is null so the getPlayer() will result in a NPE. A check if the manager is not null would fix the issue I guess.

**Comment by eneim** [comment]
@supes What version are you using? I think it was fixed in latest release (The error was a wrong way to get Manager instance from cache).

**Comment by eneim** [comment]
Fixed in 2.3.0
