### ISSUE TITLE
NullPointerException when fast scroll videos

### ISSUE THREAD

**Issue by smithc42** [eneim/toro#219]
I've implemented ToroPlayer in my ViewHolder (direct copy/paste from [here](https://github.com/eneim/toro/blob/dev-v3/app/src/main/java/im/ene/toro/sample/common/SimpleExoPlayerViewHolder.java)) and videos play/pause correctly when I scroll normally/slowly. I'm having an issue when I scroll fast (fling) through the recyclerview, I get a null pointer and the app crashes. Below is the stack trace:
```AndroidRuntime: FATAL EXCEPTION: main Process: #########, PID: 22576
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getLocationOnScreen(int[])' on a null object reference
   at im.ene.toro.widget.Common.allowsToPlay(Common.java:71)
   at im.ene.toro.widget.Container$1.onGlobalLayout(Container.java:156)
   at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:889)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2070)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
   at android.view.Choreographer.doCallbacks(Choreographer.java:590)
   at android.view.Choreographer.doFrame(Choreographer.java:560)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:145)
   at android.app.ActivityThread.main(ActivityThread.java:5951)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
``` 
- Toro version:  3.0.0-alpha1
- Exoplayer version: r2.4.0
- Compile SDK: 25
- Target SDK: 25
- Build Tools: 25.0.3
- Support Library: 25.4.0
- Gradle wrapper: 4.0
- Devices tested on: Samsung Galaxy S4 (5.0.1), OnePlus 2 (6.0.1), Emulator (Pixel, 7.1.1)

**Comment by eneim** [comment]
@smithc42 thanks a lot. I really don't expect this, because from your log I could see the NPE occurs for the playerView which should be created from a ViewHolder's constructor. So this can be a bug of system as well ... let me try to reproduce this. It can easily be "fixed" by a null check at allowsToPlay method, but it doesn't make sense though :D.

**Comment by smithc42** [comment]
@eneim No problem. Yeah, a null check is just hiding the issue. I'll try to reproduce in the demo app!
