### ISSUE TITLE
Source error.

### ISSUE THREAD

**Issue by JaydeepRathod** [eneim/toro#236]
Unexpected exception loading stream
                                                         java.lang.IllegalStateException
                                                             at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:79)
                                                             at com.google.android.exoplayer2.extractor.mp4.AtomParsers.parseStbl(AtomParsers.java:200)
                                                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processMoovAtom(Mp4Extractor.java:341)
                                                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.processAtomEnded(Mp4Extractor.java:276)
                                                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:267)
                                                             at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:147)
                                                             at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:652)
                                                             at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                             at java.lang.Thread.run(Thread.java:818)

--------------------------------------------------------------------------
--------------------------------------------------------------------------
--------------------------------------------------------------------------

Source error.
                                                                      com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 416
                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:211)
                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640)
                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                          at java.lang.Thread.run(Thread.java:818)
                                                                       Caused by: com.google.android.exoplayer2.upstream.DataSourceException
                                                                          at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:214)
                                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123) 
                                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:640) 
                                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295) 
                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                          at java.lang.Thread.run(Thread.java:818) 
0
--------------------------------------------------------------------------
--------------------------------------------------------------------------
--------------------------------------------------------------------------
 Internal runtime error.
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
                                                                          at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2379)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:899)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:510)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
07-25 18:31:16.870 12147-16837/com.bstar.app E/ExoPlayerImplInternal: Stop failed.
                                                                      java.lang.IllegalStateException
                                                                          at android.media.MediaCodec.native_stop(Native Method)
                                                                          at android.media.MediaCodec.stop(MediaCodec.java:1901)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:455)
                                                                          at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:409)
                                                                          at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:283)
                                                                          at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:147)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:709)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:684)
                                                                          at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:364)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by eneim** [comment]
@JaydeepRathod This happens to be an error from your Video, please double check it, make sure it works with ExoPlayer demo app or MediaPlayer API first.
