### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lim/ene/toro/exoplayer/ExoPlayerHelper$EventListener

### ISSUE THREAD

**Issue by jonathansds** [eneim/toro#249]
Toro Version: im.ene.toro3:toro:3.0.1-B1

I just implemented my viewholder as suggested in the README file:

    private class FeedItemViewHolderVideo extends RecyclerView.ViewHolder implements ToroPlayer{
        @Nullable
        SimpleExoPlayerViewHelper helper;
        FeedViewHolderHelper feedViewHolderHelper;

        FeedItemViewHolderVideo(View itemView) {
            super(itemView);

            feedViewHolderHelper = new FeedViewHolderHelper(itemView);
        }

        @Override
        public void initialize(@NonNull Container container, @Nullable PlaybackInfo playbackInfo) {
            if (helper == null) {
                //APP CRASHES WHEN EXECUTING LINE BELOW
                helper = new SimpleExoPlayerViewHelper(container, this, feedViewHolderHelper.videoUri);
            }
            helper.initialize(playbackInfo);
        }
        ...
    }

Exception:

> java.lang.NoClassDefFoundError: Failed resolution of: Lim/ene/toro/exoplayer/ExoPlayerHelper$EventListener;
                                                                    at com.jd.myworld.adapter.FeedRecycleAdapter$FeedItemViewHolderVideo.initialize(FeedRecycleAdapter.java:168)
                                                                    at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:68)
                                                                    at im.ene.toro.widget.Container$1.onGlobalLayout(Container.java:167)
                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:981)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2456)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:670)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                 Caused by: java.lang.ClassNotFoundException: im.ene.toro.exoplayer.ExoPlayerHelper$EventListener
                                                                    at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                    at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                    at com.jd.myworld.adapter.FeedRecycleAdapter$FeedItemViewHolderVideo.initialize(FeedRecycleAdapter.java:168) 
                                                                    at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:68) 
                                                                    at im.ene.toro.widget.Container$1.onGlobalLayout(Container.java:167) 
                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:981) 
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2456) 
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550) 
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:670) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945) 
                                                                    at android.os.Handler.handleCallback(Handler.java:751) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
                                                                 Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
                                                                    at com.jd.myworld.adapter.FeedRecycleAdapter$FeedItemViewHolderVideo.initialize(FeedRecycleAdapter.java:168) 
                                                                    at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:68) 
                                                                    at im.ene.toro.widget.Container$1.onGlobalLayout(Container.java:167) 
                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:981) 
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2456) 
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550) 
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:670) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945) 
                                                                    at android.os.Handler.handleCallback(Handler.java:751) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
                                                                 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.jd.myworld-1/base.apk"],nativeLibraryDirectories=[/data/app/com.jd.myworld-1/lib/arm64, /data/app/com.jd.myworld-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                    at com.jd.myworld.adapter.FeedRecycleAdapter$FeedItemViewHolderVideo.initialize(FeedRecycleAdapter.java:168) 
                                                                    at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:68) 
                                                                    at im.ene.toro.widget.Container$1.onGlobalLayout(Container.java:167) 
                                                                    at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:981) 
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2456) 
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1550) 
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7189) 
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959) 
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734) 
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:670) 
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945) 
                                                                    at android.os.Handler.handleCallback(Handler.java:751) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                    at android.os.Looper.loop(Looper.java:154) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by eneim** [comment]
@jonathansds How many methods you have on your build? Also did you change ExoPlayer version?

You can use this to check method count at build time: https://github.com/KeepSafe/dexcount-gradle-plugin

**Comment by jonathansds** [comment]
@eneim I was using Android VideoView so I changed to the Exoplayer version to 2.5.1 now the error is:

> 09-04 07:28:58.292 23770-23770/com.jd.myworld E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: com.jd.myworld, PID: 23770
                                                                java.lang.NoSuchMethodError: No virtual method addListener(Lcom/google/android/exoplayer2/ExoPlayer$EventListener;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/com.jd.myworld-1/base.apk:classes125.dex)
                                                                    at im.ene.toro.exoplayer.ExoPlayerHelper.prepare(ExoPlayerHelper.java:194)
                                                                    at im.ene.toro.exoplayer.ExoPlayerHelper.prepare(ExoPlayerHelper.java:168)
                                                                    at im.ene.toro.exoplayer.ExoPlayerHelper.prepare(ExoPlayerHelper.java:133)
                                                                    at im.ene.toro.exoplayer.SimpleExoPlayerViewHelper.initialize(SimpleExoPlayerViewHelper.java:75)
                                                                    at com.jd.myworld.adapter.FeedRecycleAdapter$FeedItemViewHolderVideo.initialize(FeedRecycleAdapter.java:168)
                                                                    at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:68)
                                                                    at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:259)
                                                                    at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4751)
                                                                    at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1434)
                                                                    at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4908)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:734)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:667)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by eneim** [comment]
@jonathansds ExoPlayer 2.5.1 has a few changes that is not really binary backward compatible. If you can stay with 2.4.x, please. I will push 3.1.0 that depends on 2.5.+ to fix this first.

**Comment by jonathansds** [comment]
Thanks @eneim , I changed the Exoplayer version to 2.4.4 and it is working fine now. Thanks a lot!
