### ISSUE TITLE
Getting crash on resume 

### ISSUE THREAD

**Issue by Anilugale** [eneim/toro#256]
java.lang.IllegalStateException: Player is playing while it is not in managed state: ViewHolder{4538d43 position=0 id=-1, oldPos=-1, pLpos:-1 invalid update undefined adapter position}
                                                                 at im.ene.toro.widget.Container.onChildDetachedFromWindow(Container.java:183)

**Comment by eneim** [comment]
@Anilugale How often this issue happen to you? On Every "onResume" ? Do you have any special setting for your Device? (for example 'Don't save Activity state' setting in Developer Setting)?

**Comment by Anilugale** [comment]
it happen when I am open full screen from the recyclerview item in separate activity. and when i am back to screen my recycler adapter is notified that time it give the exception.

**Comment by eneim** [comment]
I see. Does the full screen activity trigger a Configuration changes? (for example: you open the full screen in landscape mode). Let me investigate this case.

**Comment by Anilugale** [comment]
not it is in portrait mode

**Comment by eneim** [comment]
@Anilugale Can you give me a snapshot of code where you setup your RecyclerView? Is it inside your onCreate or onResume? Thanks.

**Comment by Anilugale** [comment]
@eneim thanks for the support. find the reason of crash. it due to wrong implementation of ToroPlayer. i have 2 holder with video and without video. i am implemented both ToroPlayer in both player that why it occur

**Comment by eneim** [comment]
@Anilugale Sounds great.

**Comment by Anilugale** [comment]
it reproduces in android 7.1.1 samsung device. toro player implement in recycler view nested ways

Toro version 3.2.0
Exo player version 2.5.3

`java.lang.IllegalStateException: Player is playing while it is not in managed state: ViewHolder{2340423 position=8 id=-1, oldPos=-1, pLpos:-1}
        at im.ene.toro.widget.Container.onChildDetachedFromWindow(Container.java:182)
        at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7145)
        at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:794)
        at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8260)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8532)
        at android.support.v7.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1371)
        at android.support.v7.widget.LinearLayoutManager.recycleViewsFromStart(LinearLayoutManager.java:1417)
        at android.support.v7.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1486)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1510)
        at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1333)
        at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1077)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4960)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
        at android.view.Choreographer.doCallbacks(Choreographer.java:705)
        at android.view.Choreographer.doFrame(Choreographer.java:637)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)`

**Comment by harshbhavsar011** [comment]
`java.lang.IllegalStateException: Player is playing while it is not in managed state: ViewHolder{2b10cca position=11 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)}` Any one found solution?
