### ISSUE TITLE
handler crash after notifying adapter

### ISSUE THREAD

**Issue by Anilugale** [eneim/toro#260]
`Handler (com.google.android.exoplayer2.upstream.Loader$ReleaseTask) {1c9c728} sending message to a Handler on a dead thread
                                                             java.lang.IllegalStateException: Handler (com.google.android.exoplayer2.upstream.Loader$ReleaseTask) {1c9c728} sending message to a Handler on a dead thread
                                                                 at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                 at android.os.Handler.enqueueMessage(Handler.java:643)
                                                                 at android.os.Handler.sendMessageAtTime(Handler.java:612)
                                                                 at android.os.Handler.sendMessageDelayed(Handler.java:582)
                                                                 at android.os.Handler.sendEmptyMessageDelayed(Handler.java:546)
                                                                 at android.os.Handler.sendEmptyMessage(Handler.java:531)
                                                                 at com.google.android.exoplayer2.upstream.Loader$ReleaseTask.run(Loader.java:423)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                 at java.lang.Thread.run(Thread.java:761)`

**Comment by anthony3444** [comment]
I have the same error. @Anilugale : did you resolve it?

**Comment by eneim** [comment]
@Anilugale Do you still have this issue?

**Comment by Anilugale** [comment]
no i am not, It not that frequent
