### ISSUE TITLE
  java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onPositionDiscontinuity(int)"

### ISSUE THREAD

**Issue by oneeall** [eneim/toro#278]
hi, I'm using toro version 3.2.0 its very cool lib thank you for this awesome lib.
I just trying to stream video in recyclerview, I follow basic usage and its running well until when the video finish and goes crash
can you give me any advice?

Logcat
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.mumu.myvideorecyclerview, PID: 32141
                  java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onPositionDiscontinuity(int)"
                      at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:273)
                      at com.google.android.exoplayer2.ExoPlayerImpl.seekTo(ExoPlayerImpl.java:230)
                      at com.google.android.exoplayer2.SimpleExoPlayer.seekTo(SimpleExoPlayer.java:672)
                      at im.ene.toro.exoplayer.ExoPlayerHelper$ComponentListener.onPlayerStateChanged(ExoPlayerHelper.java:333)
                      at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:171)
                      at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:627)
                      at im.ene.toro.exoplayer.ExoPlayerHelper$ComponentListener.onPlayerStateChanged(ExoPlayerHelper.java:332)
                      at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:462)
                      at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:100)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by eneim** [comment]
@oneeall 3.2.0 is not updated with ExoPlayer 2.6.0, please wait a few days for 3.3.0 artifact. Sorry for this inconvenience.

**Comment by jemshit** [comment]
so exoplayer r2.5.4 is used?

**Comment by eneim** [comment]
@jemshit Yes :).

**Comment by bragonya1992** [comment]
Sorry, someone know how to resolve abstract method issue in exoplayer?

Regards.

**Comment by eneim** [comment]
@bragonya1992 There is a dependency relationship between Toro version and ExoPlayer version. Can you clarify which version of each you are having in your build.gradle?
