### ISSUE TITLE
ExoPlayer2 crash: sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by anthony3444** [eneim/toro#284]
Hi!

Often, when I scoll in my recyclerview the player doesn't work... And the trace related to this problem is:

```
01-03 09:35:54.954 32571-32571/com.mycompagny.dev I/ExoPlayerImpl: Release ed7940d [ExoPlayerLib/2.5.4] [athene_f, Moto G (4), motorola, 24] [goog.exo.core, goog.exo.ui]
01-03 09:35:54.958 32571-1860/com.mycompagny.dev I/MediaCodec: (0x859c2a00) stop
01-03 09:35:54.969 32571-1864/com.mycompagny.dev D/DisplayPanel: iPanelNotifyTextureVideoState: state=0
01-03 09:35:54.971 32571-1860/com.mycompagny.dev I/MediaCodec: (0x859c2a00) release
01-03 09:35:54.980 32571-1860/com.mycompagny.dev I/MediaCodec: (0x859c2b40) stop
01-03 09:35:54.985 32571-1860/com.mycompagny.dev I/MediaCodec: (0x859c2b40) release
01-03 09:35:55.094 32571-1875/com.mycompagny.dev W/MessageQueue: Handler (com.google.android.exoplayer2.upstream.Loader$ReleaseTask) {979dc1c} sending message to a Handler on a dead thread
                                                            java.lang.IllegalStateException: Handler (com.google.android.exoplayer2.upstream.Loader$ReleaseTask) {979dc1c} sending message to a Handler on a dead thread
                                                                at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                at android.os.Handler.enqueueMessage(Handler.java:643)
                                                                at android.os.Handler.sendMessageAtTime(Handler.java:612)
                                                                at android.os.Handler.sendMessageDelayed(Handler.java:582)
                                                                at android.os.Handler.sendEmptyMessageDelayed(Handler.java:546)
                                                                at android.os.Handler.sendEmptyMessage(Handler.java:531)
                                                                at com.google.android.exoplayer2.upstream.Loader$ReleaseTask.run(Loader.java:423)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                at java.lang.Thread.run(Thread.java:761)
```
My config:

implementation "im.ene.toro3:toro:3.2.0"
implementation "com.google.android.exoplayer:exoplayer:r2.5.4"

Thank you very much for your support!

**Comment by anthony3444** [comment]
Ok, I've migrated to the new Toro version 3.3.0 and it works now without this crash!

Perfect!

**Comment by eneim** [comment]
@anthony3444 I guess this doesn't crash your App but the logcat shows yellow warning? It is a known issues of ExoPlayer actually, it should be fine I think.
