### ISSUE TITLE
exception !!!!

### ISSUE THREAD

**Issue by ismailtosun** [eneim/toro#300]
when i run sample app , I got this exception ? 

``` 
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: im.ene.toro.youtube, PID: 943
                  java.lang.RuntimeException: YouTube init error: SERVICE_MISSING
                      at im.ene.toro.youtube.YouTubePlayerHelper$1.onInitializationFailure(YouTubePlayerHelper.java:166)
                      at com.google.android.youtube.player.YouTubePlayerView.a(Unknown Source)
                      at com.google.android.youtube.player.YouTubePlayerView.a(Unknown Source)
                      at com.google.android.youtube.player.YouTubePlayerView$2.a(Unknown Source)
                      at com.google.android.youtube.player.internal.r.a(Unknown Source)
                      at com.google.android.youtube.player.internal.r$a.handleMessage(Unknown Source)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
I/CrashlyticsCore: Crashlytics report upload complete: 5A7CB01E00A5-0001-03AF-AC89DBC7FBF5
```

**Comment by eneim** [comment]
@ismailtosun Hi there. This is an error thrown by YouTubePlayerAPI, can you give me some information about: what Device you are using, Android version, Toro version, your Youtube App (in device) version (find it in Play Store).
