### ISSUE TITLE
PLAYBACK ERROR

### ISSUE THREAD

**Issue by BobFactory** [eneim/toro#318]
Internal playback issue

Hi,

Thanks for this awesome library firstly.
I have been facing an issue in which if the user fastly scrolls to the last item in the recyclerview and then returns back to the first position and then minimizes the app and resumes it, then after some time there is an E/ExoPlayerImplInternal: Playback error. Below is the stacktrace of it.

After this, every exoplayer in the application throws an error as I am assuming there is no more room for further rendering. I understand that this looks more like an exoplayer issue. What I want to know is if toroplayer is handlingon  any thing on the onresume part of the application as I have noticed that the player stars playing when the activity resumes even when it was set to pause.

`E/ExoPlayerImplInternal: Playback error.
                                                                            com.google.android.exoplayer2.ExoPlaybackException
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:420)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898)
                                                                                at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:284)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                             Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.aac.decoder, Format(2, null, audio/mp4a-latm, -1, eng, [-1, -1, -1.0], [2, 44100])  at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:407) 
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
                                                                                at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:284) 
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                             Caused by: java.lang.IllegalArgumentException: start failed
                                                                                at android.media.MediaCodec.native_start(Native Method)
                                                                                at android.media.MediaCodec.start(MediaCodec.java:1991)  at android.media.MediaCodec.start(MediaCodec.java:1991)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:400)
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:898) 
                                                                                at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.onInputFormatChanged(MediaCodecAudioRenderer.java:284) 
                                                                                at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:551) 
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
                                                                                at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) ` 

  Toro version - v3
  Android version - Android 8.0.0 (Oreo), Android 7.1.0 (Nougat)
  Device name - Google Pixel 1, Nexus 6P

**Comment by eneim** [comment]
@BobFactory Can you also give me some info about the media file that can reproduce this issue? If the file need to be kept secret, please send it to me via nam@ene.im. Thanks.

**Comment by eneim** [comment]
@BobFactory Do you mean that user pause the player by clicking to the button? This case requires more work actually. The good part is I'm preparing it in next release ...

**Comment by BobFactory** [comment]
Yes, I need the player to work in a fashion that when the user comes to the recycler view then the video auto-plays but it should not start when the activity resumes it should maintain the state set by the mHelper.pause(); method. Is there any workaround I can have for this. 

Can there be a method in which at least the video frame is retained when the user resumes the activity, I am noticing that when the user pauses the video in between and goes to the background and when he returns then there is a black screen and the video plays again. I need that at least the video is retained in the player and not re-initializing the entire player.

**Comment by eneim** [comment]
@BobFactory Hmm. mHelper.pause() is called automatically. To sort out your thought, it would work as below:

- User open the app, the list has a Video on screen and it starts playing automatically.
- User do nothing, and press 'Home' so the App enters stopping state.
- User open the App again, and as the UI doesn't change, there will be the Video on screen, **But** Here you want the Video won't start playing as before?

**Comment by eneim** [comment]
@BobFactory About your second question, there is no trivial way to retain the video frame. It requires extra work and if you can try Facebook app, they put a thumbnail on top of it each time the Video pause/resume. I guess it is what I would try to do.

**Comment by BobFactory** [comment]
@eneim : comment 1 is exactly what i want to achieve, right now the video auto-plays whenever there is any interaction in the recyclerview. I want such thing that if the user has paused it or we pause the player programmatically by calling pause() method, then the player should auto start as it does now when the user returns from the background.

About the second point is something that I think that is a limitation in andorid. Although my ios brothers have no problem in doing this with their native player. 

Thanks for all the support, I will try to figure some work around this issue.

**Comment by eneim** [comment]
@BobFactory FYI the first point is not the original intent of Toro. Also, it is not trivial to know your Activity/UI 'resumes for the first time' or 'resumes for the n-th time'. If you want to do this, sadly I can only have comment or suggestion, not a official support. And it is low priority as I'm finalizing 3.4.2 release.

**Comment by BobFactory** [comment]
@eneim I have tweaked a little bit of your code implementation and with some manual handling, I was able to achieve the desired functionality. I have just one question for you, how many exoplayer instances are created when recyclerview is initialized ?

**Comment by eneim** [comment]
@BobFactory The number of ExoPlayer instances equals to how many Video on screen you have that time. So if you have 10 Videos on screen, it will prepare 10 instances. Though, the actual resource consuming task is the call to ExoPlayer#prepare(MediaSource) and in 3.4.1 I make it to be lazy, so that those 10 instances won't start preparing resource all together. The less Video you have, the less instances they are.

**Comment by BobFactory** [comment]
@eneim 👍 Thanks for clarifying the logic, Clearly a good implementation, Although I am under the impression from the exoplayer docs that creating player instances holds resources such as MEDIA CODEC and other resources required for rendering. And form exoplayer issues people have suggested to create only 2 instances of exoplayer and switching media between them and playing. You should probably check on those also. Nonetheless, I have struggled a lot make this implementation on my own and yours is the only one that works, just make sure you are holding only the required resources as some android devices have low memory and can lead to player errors.

Good Luck and Thanks!!
