### ISSUE TITLE
NullPointerException inside PlayerManager

### ISSUE THREAD

**Issue by alexglobalbit** [eneim/toro#352]
I have a nested recyclerview with videos and images, and some time when scrolling, this exception occur:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.Handler.removeCallbacksAndMessages(java.lang.Object)' on a null object reference
        at im.ene.toro.widget.PlayerManager.detachPlayer(PlayerManager.java:52)
        at im.ene.toro.widget.Container.onChildDetachedFromWindow(Container.java:265)
        at android.support.v7.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7145)
        at android.support.v7.widget.RecyclerView$5.removeViewAt(RecyclerView.java:794)
        at android.support.v7.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8260)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:8532)
        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleAllViews(RecyclerView.java:9944)
        at android.support.v7.widget.RecyclerView.removeAndRecycleViews(RecyclerView.java:1101)
        at android.support.v7.widget.RecyclerView.setAdapterInternal(RecyclerView.java:1124)
        at android.support.v7.widget.RecyclerView.setAdapter(RecyclerView.java:1083)
        at im.ene.toro.widget.Container.setAdapter(Container.java:417)
  
This is happening in PlayerManager method:
`boolean detachPlayer(@NonNull ToroPlayer player) {
    handler.removeCallbacksAndMessages(player);
    return players.remove(player);
  }`
'handler' object is null.

  - Toro version - 3.5.2
  - Android 7
  - Nexus 6

**Comment by eneim** [comment]
@alexglobalbit Seem that it is called before RecyclerView is attached or after it is detached. And I have the null check for handler everywhere accept a few place ... Thanks for pointing this out I will fix it in next release.

**Comment by eneim** [comment]
@harshbhavsar011 fixed locally, I will consider to update a snapshot build soon.

**Comment by eneim** [comment]
Please try the fix in 3.6.0.2802-SNAPSHOT :D
