### ISSUE TITLE
NullPointerException: IN -> im.ene.toro.widget.Container.setLayoutManager

### ISSUE THREAD

**Issue by wvmoreira** [eneim/toro#394]
Hi guys,

I'm trying to use the TOTO version:
```
     implementation "im.ene.toro3: toro: $ {latest_release}"
     implementation "im.ene.toro3: toro-ext-exoplayer: $ {latest_release}" // to get ExoPlayer support
```

ext.supportLibraryVersion = '27 .1.1 '
**ext.latest_release = '3.6.0.2802';** // - SNAPSHOT '; //' 3.5.2 '// // TODO check above for latest version
ext.constrainLayoutVersion = '1.1.3'
ext.exoPlayer2Version = '2.8.2'
ext.glide = '4.8.0'

But every time it arrives in that part of the code the APP is interrupted.
```
     ButterKnife.bind (this);

     layoutManager = new LinearLayoutManager (this);
     container.setLayoutManager (layoutManager);
```

**My layoutManager = null**

What am I missing? I'm using the same examples you have here on Github.
I just copied the source codes and pasted it into my project.

does not have any changes.

I already lost 2 days investigating the cause and I can not find out!

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.pazo.myapplication, PID: 25270
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.pazo.myapplication/br.com.pazo.sample.basic.BasicListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void im.ene.toro.widget.Container.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void im.ene.toro.widget.Container.setLayoutManager(android.support.v7.widget.RecyclerView$LayoutManager)' on a null object reference
        at br.com.pazo.sample.basic.BasicListActivity.onCreate(BasicListActivity.java:48)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)`

**Comment by wvmoreira** [comment]
@eneim my friend was able to solve it!
Failed to put butterknife annotationProcessor

Now I need a lot of help!
In your facebook example you use an ENUM, how can I use a LIST obtained through JSON?

I'll buy you a Coffee! The library is very good!

**Comment by eneim** [comment]
@wvmoreira Haha Ok. Enum is just a way to make things simpler.

Saying you have the following json from network:

```js
{
  id: "ID12345",
  title: "My cool video",
  description: "Description of my cool video",
  url: "https://site.domain/path1/path2/video_name.mp4",
  width: 1920,
  height: 1080
}
```

You will need a java object class (POJO) or a kotlin data class to represent this object:

```java
public class MyVideo {
  String id;
  String title;
  String description;
  String url;
  int width;
  int height;
}
```

You can use gson or moshi to convert the json response to that object class above. I assume you are able to do so.

The next step is to integrate Toro into your app and use this MyVideo object.
If you see how to create a ``ExoPlayerViewHelper``, you may notice this constructor:

```java
helper = new ExoPlayerViewHelper(this, mediaUri)
```

So what you gonna do here is:

[1] Pass the MyVideo item to your ViewHolder (also a ToroPlayer).
[2] Create a Uri for the MyVideo's url: Uri videoUri = Uri.parse(myVideo.url)
[3] Build the helper: helper = new ExoPlayerViewHelper(this, mediaUri) (here ``this`` is the ViewHolder).

Please take the suggestion above and see if it helps.

**Comment by wvmoreira** [comment]
@eneim 
I already did it here! I have already integrated with a Json return service.
:-)

One more question regarding the 3 AppCompatTextView:
fb_button_like
fb_button_comment
fb_button_share

How and where can I place the click event? Clicking Share would like to download the video and share it through some social network.

Is it better to use a class to download or the videos? Are they cached? If they are in cache there is the possibility to pick them up and send by whatsAPP?

**Comment by wvmoreira** [comment]
@eneim 
I made the listener .setOnClickListener (clickListener);

However when you click the like button it opens the MoreVideosFragment
Always execute the following button:
```
   @Override
                      void onItemClick(@NonNull TimelineViewHolder viewHolder, @NonNull View view,
                                       @NonNull FbItem item, int position) {
                        if (viewHolder instanceof ToroPlayer && item instanceof FbVideo) {
                          PlaybackInfo info = ((ToroPlayer) viewHolder).getCurrentPlaybackInfo();
                          MoreVideosFragment moreVideos =
                                  MoreVideosFragment.newInstance(position, (FbVideo) item, info);
                          moreVideos.show(getChildFragmentManager(), MoreVideosFragment.TAG);
                        }
                      }
```

I would like to handle the different listener, where can I be wrong?
