### ISSUE TITLE
Playing videos from RTSP protocol

### ISSUE THREAD

**Issue by omerGlobalBIt** [eneim/toro#413]
@eneim Hi, I wanted to know if the library supports RTSP protocols. I have seen that support for this protocol is added to ExoPlayer ([https://github.com/google/ExoPlayer/pull/3854])
 but for some reason i cant play it and get url malformed exception from exoplayer:
`com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to rtsp://104.196.130.249:1935/gabriel/00-00-00-00-00-10.stream
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.net.MalformedURLException: unknown protocol: rtsp
        at java.net.URL.<init>(URL.java:597)
        at java.net.URL.<init>(URL.java:487)
        at java.net.URL.<init>(URL.java:436)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:426)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479) 
        at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83) 
        at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) `

These are my module builde dependecies:
`ext {
        latest_snapshot = '3.7.0.2901-SNAPSHOT' // TODO check above for latest version
        // below: other dependencies' versions maybe
    }

    dependencies {
        implementation "im.ene.toro3:toro:${latest_snapshot}"
        implementation "im.ene.toro3:toro-ext-exoplayer:${latest_snapshot}"  // to get ExoPlayer support
    }

    implementation ("com.google.android.exoplayer:exoplayer:${rootProject.ext.exoPlayer2Version}") {
        exclude group: 'com.android.support'
    }`

And these are project level build properties: (other dependecies are as in README)
`ext {
    exoPlayer2Version = '2.9.3'
}`

Thanks for the help

**Comment by omerGlobalBIt** [comment]
Hi @eneim Thank for your quick reply.
Sorry but cant share workable url but the exception thrown says "unknown protocol rtsp" so i dont think its about the url. Furthermore, when i show it in regular videoview it works just fine do you want me to also test it in a regular exoPlayer?

**Comment by eneim** [comment]
@omerGlobalBIt Oh I just check the PR you mention. It is not merged to ExoPlayer yet, which means that RSTP is not yet supported by ExoPlayer. I guess you need to wait a little bit more. You can file an issue to ExoPlayer to speed the up.

The error clearly says it doesn't acknowledge about the protocol 'rstp'.

**Comment by omerGlobalBIt** [comment]
Oh ok my bad thank you @eneim
