### ISSUE TITLE
Proguard rules issue

### ISSUE THREAD

**Issue by charlizesmith** [eneim/toro#414]
Hi,
  I have implemented Toro player with default controllers. Referred Toro-basic and Toro-facebook demo for the same.The code works fine with debug environment but creating release apk with applying proguard rules is giving trouble. 
  
Toro version: **3.6.2.2804**.

Continuously facing the following issue :-

2019-01-29 13:10:08.548 9864-9864/com.otpdetection.example.torovideodemoproject E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.otpdetection.example.torovideodemoproject, PID: 9864
    **java.lang.IncompatibleClassChangeError: The method 'void com.google.android.exoplayer2.ui.PlayerControlView.hideAfterTimeout()' was expected to be of type direct but instead was found to be of type virtual (declaration of 'com.google.android.exoplayer2.ui.PlayerControlView' appears in /data/app/com.otpdetection.example.torovideodemoproject-1/base.apk)**
        at com.google.android.exoplayer2.ui.PlayerControlView.show(PlayerControlView.java:564)
        at com.google.android.exoplayer2.ui.PlayerView.showController(PlayerView.java:1137)
        at com.google.android.exoplayer2.ui.PlayerView.maybeShowController(PlayerView.java:1116)
        at com.google.android.exoplayer2.ui.PlayerView.setPlayer(PlayerView.java:563)
        at wow.tt.j(PlayableImpl.java:240)
        at wow.tt.g(PlayableImpl.java:102)
        at wow.tp.g(ExoPlayable.java:47)
        at wow.tq.b(ExoPlayerViewHelper.java:108)
        at wow.tb.c(VideoViewHolder.java:179)
        at wow.uc.a(PlayerManager.java:85)
        at wow.uc.a(PlayerManager.java:75)
        at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:335)
        at im.ene.toro.widget.Container$a.handleMessage(Container.java:796)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2019-01-29 13:10:09.782 31088-31957/? E/Sensors: handleToDriver handle(0).

**Added following proguard rule for Toro Library**

-optimizationpasses 5
-repackageclasses 'wow'

-keepclassmembernames class com.google.android.exoplayer2.ui.PlayerControlView {
  java.lang.Runnable hideAction;
  void hideAfterTimeout();
}

**Tried the combination of following proguard rules :-**

-keep class com.google.android.exoplayer2.** {*;}
-keep interface com.google.android.exoplayer2.** {*;}
-keep enum com.google.android.exoplayer2.** {*;}
-dontwarn com.google.android.exoplayer2.**

-keep class im.ene.toro.** {*;}
-keep interface im.ene.toro.** { *; }
-keep enum im.ene.toro.**{ *; }
-dontwarn im.ene.toro.**

**Comment by eneim** [comment]
@charlizesmith Replied you in gitter. Can you tell me which version of Android Studio you use to build? I tried on 3.3 and it builds my demo app successfully.

**Comment by charlizesmith** [comment]
I have solved the issue by removing following proguard rules.

-repackageclasses ''
-allowaccessmodification

Thank you for help.
