### ISSUE TITLE
Error when play. surfaceSizeChanged

### ISSUE THREAD

**Issue by yongju-jin** [eneim/toro#445]
```
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.video.VideoListener.onSurfaceSizeChanged(int, int)"
        at com.google.android.exoplayer2.SimpleExoPlayer.maybeNotifySurfaceSizeChanged(SimpleExoPlayer.java:1172)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceHolder(SimpleExoPlayer.java:338)
        at com.google.android.exoplayer2.SimpleExoPlayer.setVideoSurfaceView(SimpleExoPlayer.java:356)
        at com.google.android.exoplayer2.ui.PlayerView.setPlayer(PlayerView.java:554)
        at im.ene.toro.exoplayer.PlayableImpl.ensurePlayerView(PlayableImpl.java:240)
        at im.ene.toro.exoplayer.PlayableImpl.play(PlayableImpl.java:102)
        at im.ene.toro.exoplayer.ExoPlayable.play(ExoPlayable.java:47)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.play(ExoPlayerViewHelper.java:108)
```
i using
```
    implementation "im.ene.toro3:toro:3.6.2.2903"
    implementation ("im.ene.toro3:toro-ext-exoplayer:3.6.2.2903")
    implementation group: 'com.google.android.exoplayer', name: 'exoplayer', version: '2.9.3'
```

my xml is
```
            <FrameLayout
                android:layout_width="0dp"
                android:layout_height="0dp"
                app:layout_constraintBottom_toTopOf="@id/tv_management_banner_video_funding"
                app:layout_constraintDimensionRatio="343:194"
                app:layout_constraintEnd_toEndOf="parent"
                app:layout_constraintStart_toStartOf="parent"
                app:layout_constraintTop_toTopOf="parent"
                app:layout_constraintVertical_chainStyle="packed"
                app:layout_constraintVertical_bias="0"
                >

                <com.google.android.exoplayer2.ui.PlayerView
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:onClick="@{() -> videoInterface.onClickVideo()}"
                    app:resize_mode="fixed_width"
                    app:use_controller="false"
                    />

                <androidx.core.widget.ContentLoadingProgressBar
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:indeterminate="false"
                    android:max="100"
                    android:progressDrawable="@drawable/progress_video"
                    android:layout_gravity="bottom"
                    />
            </FrameLayout>
```

and video url is not invalid.

**Comment by eneim** [comment]
@yongju-jin Is this reproducable all the time?

**Comment by bakhytk** [comment]
Have the same issue on the real device (LG), but tests on the simulator and Samsung were ok.

Is there any update about this or some thoughts how to fix it?

Thanks

**Comment by lglossman-ring** [comment]
@bakhytk Add the following line to your `gradle.properties` file:

```android.enableDexingArtifactTransform=false```

The problem resides in a new feature of the gradle build tools 3.5 where it tries to optimize external dependencies as well and it strips default method implementations from exoplayer.
According to the android team issue tracker this issue should be fixed by correctly declaring all dependencies and transient dependencies on the `pom.xml` but I couldn't find any solution other than this.

**Comment by bakhytk** [comment]
Awesome! It fixes the problem.

Thank you, @lglossman-ring

**Comment by shukla147** [comment]
Thank you man @lglossman-ring

**Comment by gitam2869** [comment]
> @bakhytk Add the following line to your `gradle.properties` file:
> 
> `android.enableDexingArtifactTransform=false`
> 
> The problem resides in a new feature of the gradle build tools 3.5 where it tries to optimize external dependencies as well and it strips default method implementations from exoplayer.
> According to the android team issue tracker this issue should be fixed by correctly declaring all dependencies and transient dependencies on the `pom.xml` but I couldn't find any solution other than this.

Thanks....!

**Comment by MartinSchaaf** [comment]
It really helped, thank you @lglossman-ring !
