### ISSUE TITLE
 No direct method <init>(Lcom/google/android/exoplayer2/RenderersFactory;

### ISSUE THREAD

**Issue by W3ondemand-Rise** [eneim/toro#465]
Getting No such method error ,here is the whole crash report .

java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/RenderersFactory;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;Lcom/google/android/exoplayer2/drm/DrmSessionManager;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/datacube.com.unetwork-y0tJXFQJxyHNrByOMwzKgA==/base.apk!classes2.dex)
        at im.ene.toro.exoplayer.ToroExoPlayer.<init>(ToroExoPlayer.java:47)
        at im.ene.toro.exoplayer.DefaultExoCreator.createPlayer(DefaultExoCreator.java:118)
        at im.ene.toro.exoplayer.ToroExo.requestPlayer(ToroExo.java:153)
        at im.ene.toro.exoplayer.PlayableImpl.ensurePlayer(PlayableImpl.java:261)
        at im.ene.toro.exoplayer.PlayableImpl.ensureMediaSource(PlayableImpl.java:251)
        at im.ene.toro.exoplayer.PlayableImpl.play(PlayableImpl.java:101)
        at im.ene.toro.exoplayer.ExoPlayable.play(ExoPlayable.java:47)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.play(ExoPlayerViewHelper.java:108)
        at datacube.com.unetwork.Inner_VP_Package.Home_Package.SimplePlayerViewHolder.play(SimplePlayerViewHolder.java:130)
        at im.ene.toro.widget.PlayerManager.play(PlayerManager.java:85)
        at im.ene.toro.widget.PlayerManager.play(PlayerManager.java:75)
        at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:335)
        at im.ene.toro.widget.Container$AnimatorHelper.handleMessage(Container.java:796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7135)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by AppleNadhi** [comment]
@W3ondemand-Rise Could you please explain how did you fix this?

**Comment by linhvnguyen9** [comment]
@AppleNadhi probably late but reverting exoplayer to version 2.10.8 did it for me
