### ISSUE TITLE
Getting NoSuchMethodError while using this libraray 

### ISSUE THREAD

**Issue by hibittushah** [eneim/toro#466]
Here is whole crash report .Please tell me what i am doing wrong here and why it is not playing videos
Am using these library version
 

>   implementation 'com.google.android.exoplayer:exoplayer:2.8.4'
>     implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.6'
>     implementation "im.ene.toro3:toro:3.6.2.2804"
>     implementation "im.ene.toro3:toro-ext-exoplayer:3.6.2.2804" 

java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/RenderersFactory;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;Lcom/google/android/exoplayer2/drm/DrmSessionManager;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/datacube.com.unetwork-y0tJXFQJxyHNrByOMwzKgA==/base.apk!classes2.dex)
        at im.ene.toro.exoplayer.ToroExoPlayer.<init>(ToroExoPlayer.java:47)
        at im.ene.toro.exoplayer.DefaultExoCreator.createPlayer(DefaultExoCreator.java:118)
        at im.ene.toro.exoplayer.ToroExo.requestPlayer(ToroExo.java:153)
        at im.ene.toro.exoplayer.PlayableImpl.ensurePlayer(PlayableImpl.java:261)
        at im.ene.toro.exoplayer.PlayableImpl.ensureMediaSource(PlayableImpl.java:251)
        at im.ene.toro.exoplayer.PlayableImpl.play(PlayableImpl.java:101)
        at im.ene.toro.exoplayer.ExoPlayable.play(ExoPlayable.java:47)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.play(ExoPlayerViewHelper.java:108)
        at datacube.com.unetwork.Inner_VP_Package.Home_Package.SimplePlayerViewHolder.play(SimplePlayerViewHolder.java:130)
        at im.ene.toro.widget.PlayerManager.play(PlayerManager.java:85)
        at im.ene.toro.widget.PlayerManager.play(PlayerManager.java:75)
        at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:335)
        at im.ene.toro.widget.Container$AnimatorHelper.handleMessage(Container.java:796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7135)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by eneim** [comment]
@hibittushah You use 2 different verions of ExoPlayer

```
implementation 'com.google.android.exoplayer:exoplayer:2.8.4'
implementation 'com.google.android.exoplayer:exoplayer-ui:2.9.6' // <-- this should be 2.8.4
```

I also suggest to use latest version available.

**Comment by hibittushah** [comment]
Thank you so much for this .
I have solved this by using same version .

**Comment by abagusw** [comment]
`java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/RenderersFactory;Lcom/google/android/exoplayer2/trackselection/TrackSelector;Lcom/google/android/exoplayer2/LoadControl;Lcom/google/android/exoplayer2/drm/DrmSessionManager;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in`
I have the same problem @eneim , this is my gradle implementation for toro and exoplayer
`    implementation 'im.ene.toro3:toro:3.6.2.2804'
    implementation "im.ene.toro3:toro-ext-exoplayer:3.6.2.2804"
    implementation 'com.google.android.exoplayer:exoplayer:2.10.3'
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.10.3'`
besides gradle, are there other reasons that could cause that issue?

**Comment by eneim** [comment]
@abagusw If you are using `toro:3.6.2.2804`, you need ExoPlayer `2.8.4`, not `2.10.3`
