### ISSUE TITLE
[Bug report] Crashed app com.google.android.exoplayer2.trackselection.DefaultTrackSelector

### ISSUE THREAD

**Issue by itmanzzz** [eneim/Toro#502]
Toro version:  latest_release = '3.6.2.2804'
Gradle:
        **implementation "im.ene.toro3:toro:${latest_release}"
        implementation "im.ene.toro3:toro-ext-exoplayer:${latest_release}"  // to get ExoPlayer support**

- Exoplayer: 
        **implementation("com.google.android.exoplayer:exoplayer:2.12.2")
        implementation 'com.google.android.exoplayer:exoplayer-ui:2.12.2'**

- Android Device: Any
- OS: Any
- Device name: Any
- Source code:
       **  override fun initialize(container: Container, playbackInfo: PlaybackInfo) {
                 if (helper == null) {
                     helper = mediaUri?.let { ExoPlayerViewHelper(this, it) }
                }
                helper?.initialize(container, playbackInfo)
        }**

- Logcat:

    java.lang.NoSuchMethodError: No direct method <init>(Lcom/google/android/exoplayer2/upstream/BandwidthMeter;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in 
        at im.ene.toro.exoplayer.DefaultExoCreator.<init>(DefaultExoCreator.java:64)**
        at im.ene.toro.exoplayer.ToroExo.getCreator(ToroExo.java:121)
        at im.ene.toro.exoplayer.ToroExo.getDefaultCreator(ToroExo.java:137)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.<init>(ExoPlayerViewHelper.java:61)
        at im.ene.toro.exoplayer.ExoPlayerViewHelper.<init>(ExoPlayerViewHelper.java:55)
        at im.ene.toro.widget.PlayerManager.initialize(PlayerManager.java:70)
        at im.ene.toro.widget.Container.onScrollStateChanged(Container.java:315)
        at im.ene.toro.widget.Container$AnimatorHelper.handleMessage(Container.java:796)

=========
- Issue: 
I'm trying to using this Toro lib in my project and implement done. But running got crashed app with log in the above.

Please help me resolve this problem. Thank you in advance!

**Comment by ashwath20** [comment]
same here

**Comment by AkhilrajNambiar** [comment]
Any solutions for this error?
