### ISSUE TITLE
Play Video in Mute Mode

### ISSUE THREAD

**Issue by ankitjain24x7** [eneim/Toro#95]
Can we play video in mute mode using Toro?

**Comment by eneim** [comment]
@ankitjain24x7 Basically yes, you will need to do some works for that. In next version (2.0, which I'm trying to push its speed up to release), there will be the method "setVolume()" for this.

**Comment by ankitjain24x7** [comment]
@eneim I try doing making video in mute mode using Toro in SimpleVideoObject class with one parameter as float value and video start playing in mute mode but whenever the list scroll the video start playing. If possible, please help me on this i will be very thankful to you.

**Comment by eneim** [comment]
@ankitjain24x7 If you are using Toro 1.2.0, you can use the onPrepared(MediaPlayer) method, use the mediaPlayer from that callback and set its volume to 0. I will try to make a sample, but my priority for 2.0 is higher, and my time is pretty narrow now, so you can look around about setting Volume with MediaPlayer. It is the same thing.

**Comment by ankitjain24x7** [comment]
Thanks a lot @eneim. Yes its done. Thanks one more time.

**Comment by ankitjain24x7** [comment]
@eneim I try integrated ExoVideoView by taking classes from your library for integration in project then in xml it look like:
    <app.com.autovideosample.exoPlayer.ExoVideoView
        android:id="@+id/video"
        android:layout_width="match_parent"
        android:layout_height="192dp"
        android:layout_gravity="center"
        />
But it always crash with :
android.view.InflateException: Binary XML file line #44: Binary XML file line #44: Error inflating class app.com.autovideosample.exoPlayer.ExoVideoView

Unable to understand and in xml also it shows :
The following classes could not be instantiated:
- app.com.autovideosample.exoPlayer.ExoVideoView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.NullPointerException   at com.google.android.exoplayer2.util.Util.getUserAgent(Util.java:677)   at app.com.autovideosample.exoPlayer.ExoVideoView.buildHttpDataSourceFactory(ExoVideoView.java:449)   at app.com.autovideosample.exoPlayer.ExoVideoView.buildDataSourceFactory(ExoVideoView.java:445)   at app.com.autovideosample.exoPlayer.ExoVideoView.buildDataSourceFactory(ExoVideoView.java:429)   at app.com.autovideosample.exoPlayer.ExoVideoView.<init>(ExoVideoView.java:178)   at app.com.autovideosample.exoPlayer.ExoVideoView.<init>(ExoVideoView.java:154)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard  

Please help me on this.

**Comment by eneim** [comment]
@ankitjain24x7 The cause is "Exception Details java.lang.NullPointerException" somewhere in your code, please debug to figure what is null and comeback here again.
